name: Deploy Lint

on:
  pull_request:
  push:
    branches: main
    paths:
      - 'manifests/api-eks/alb/**'
    

jobs:
  api-eks-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compute modified files
        id: added_modified_files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.(yml|yaml)'
        continue-on-error: true

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Install yaml parser
        run: pip install ruamel.yaml

      - name: Run API linter
        run: python .github/workflows/api_linter.py

      


        
