name: Deploy Lint

on:
  pull_request:
  push:
    branches: main

jobs:
  api-eks-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compute modified files
        id: added_modified_files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: 'alb/(stg/*.yaml|prd/*.yaml)'
        continue-on-error: true

      - name: Stop if no modified files
      
        if: steps.added_modified_files.outputs.any_changed == 'true'

        uses: actions/setup-python@v2
        run: pip install ruamel.yaml
        run: python .github/workflows/api_linter.py

      


        
